// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Run `npm run generate` after updating vendor/sdk-generation or openapi/config.json.

import type {
	IDataObject,
	IExecuteFunctions,
	IHttpRequestOptions,
	INodeExecutionData,
	INodeProperties,
} from 'n8n-workflow';

const showOnlyForAccount = {
	resource: ['account'],
};

const showOnlyForAccountGetUsage = {
	operation: ['getUsage'],
	resource: ['account'],
};

export const accountDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnlyForAccount },
		options: [
			{
				name: 'Get Usage',
				value: 'getUsage',
				action: 'Get account usage',
				description: 'Get account usage statistics',
			},
		],
		default: 'getUsage',
	},
	// Get Usage
	{
		displayName: 'Start Date',
		name: 'startDate',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'YYYY-MM-DD',
		description: 'Start date for the usage period (format: YYYY-MM-DD)',
		displayOptions: { show: showOnlyForAccountGetUsage },
	},
	{
		displayName: 'End Date',
		name: 'endDate',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'YYYY-MM-DD',
		description: 'End date for the usage period (format: YYYY-MM-DD)',
		displayOptions: { show: showOnlyForAccountGetUsage },
	},
];

export async function executeAccount(
	this: IExecuteFunctions,
	i: number,
): Promise<INodeExecutionData[]> {
	const operation = this.getNodeParameter('operation', i) as string;

	let options: IHttpRequestOptions;

	switch (operation) {
		case 'getUsage': {
			const startDate = this.getNodeParameter('startDate', i) as string;
			const endDate = this.getNodeParameter('endDate', i) as string;
			options = {
				method: 'GET',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/accounts/usage',
				qs: { startDate, endDate },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			if (Array.isArray(responseData)) {
				return this.helpers.returnJsonArray(responseData as IDataObject[]);
			}
			return [{ json: responseData as IDataObject }];
		}
		default:
			throw new Error(`Unsupported account operation: ${operation}`);
	}
}
