// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Run `npm run generate` after updating vendor/sdk-generation or openapi/config.json.
/* eslint-disable */

import type {
	IDataObject,
	IExecuteFunctions,
	IHttpRequestOptions,
	INodeExecutionData,
	INodeProperties,
} from 'n8n-workflow';

const showOnlyForFile = {
	resource: ['file'],
};

const showOnlyForFileGet = {
	operation: ['get'],
	resource: ['file'],
};

const showOnlyForFileDelete = {
	operation: ['delete'],
	resource: ['file'],
};

const showOnlyForFileCopy = {
	operation: ['copy'],
	resource: ['file'],
};

const showOnlyForFileMove = {
	operation: ['move'],
	resource: ['file'],
};

const showOnlyForFileRename = {
	operation: ['rename'],
	resource: ['file'],
};

const showOnlyForFileBulkDelete = {
	operation: ['bulkDelete'],
	resource: ['file'],
};

const showOnlyForFileBulkAddTags = {
	operation: ['bulkAddTags'],
	resource: ['file'],
};

const showOnlyForFileBulkRemoveTags = {
	operation: ['bulkRemoveTags'],
	resource: ['file'],
};

const showOnlyForFileBulkRemoveAITags = {
	operation: ['bulkRemoveAITags'],
	resource: ['file'],
};

export const fileDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnlyForFile },
		options: [
			{
				name: 'Bulk Add Tags',
				value: 'bulkAddTags',
				action: 'Bulk add tags to files',
				description: 'Add tags to multiple files',
			},
			{
				name: 'Bulk Delete',
				value: 'bulkDelete',
				action: 'Bulk delete files',
				description: 'Delete multiple files by their IDs',
			},
			{
				name: 'Bulk Remove AI Tags',
				value: 'bulkRemoveAITags',
				action: 'Bulk remove AI tags from files',
				description: 'Remove AI tags from multiple files',
			},
			{
				name: 'Bulk Remove Tags',
				value: 'bulkRemoveTags',
				action: 'Bulk remove tags from files',
				description: 'Remove tags from multiple files',
			},
			{
				name: 'Copy',
				value: 'copy',
				action: 'Copy a file',
				description: 'Copy a file to another location',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a file',
				description: 'Delete a file by its ID',
			},
			{
				name: 'Get Details',
				value: 'get',
				action: 'Get file details',
				description: 'Get details of a file by its ID',
			},
			{
				name: 'Move',
				value: 'move',
				action: 'Move a file',
				description: 'Move a file to another location',
			},
			{
				name: 'Rename',
				value: 'rename',
				action: 'Rename a file',
				description: 'Rename a file',
			},
		],
		default: 'get',
	},
	// Get Details
	{
		displayName: 'File ID',
		name: 'fileId',
		type: 'string',
		required: true,
		default: '',
		description: 'The unique ID of the file',
		displayOptions: { show: showOnlyForFileGet },
	},
	// Delete
	{
		displayName: 'File ID',
		name: 'fileId',
		type: 'string',
		required: true,
		default: '',
		description: 'The unique ID of the file to delete',
		displayOptions: { show: showOnlyForFileDelete },
	},
	// Copy
	{
		displayName: 'Source File Path',
		name: 'sourceFilePath',
		type: 'string',
		required: true,
		default: '',
		description: 'The full path of the file to copy (e.g. /path/to/file.jpg)',
		displayOptions: { show: showOnlyForFileCopy },
	},
	{
		displayName: 'Destination Path',
		name: 'destinationPath',
		type: 'string',
		required: true,
		default: '',
		description: 'The folder path where the file should be copied to',
		displayOptions: { show: showOnlyForFileCopy },
	},
	{
		displayName: 'Include File Versions',
		name: 'includeFileVersions',
		type: 'boolean',
		default: false,
		description: 'Whether to copy all file versions',
		displayOptions: { show: showOnlyForFileCopy },
	},
	// Move
	{
		displayName: 'Source File Path',
		name: 'sourceFilePath',
		type: 'string',
		required: true,
		default: '',
		description: 'The full path of the file to move (e.g. /path/to/file.jpg)',
		displayOptions: { show: showOnlyForFileMove },
	},
	{
		displayName: 'Destination Path',
		name: 'destinationPath',
		type: 'string',
		required: true,
		default: '',
		description: 'The folder path where the file should be moved to',
		displayOptions: { show: showOnlyForFileMove },
	},
	// Rename
	{
		displayName: 'File Path',
		name: 'filePath',
		type: 'string',
		required: true,
		default: '',
		description: 'The full path of the file to rename (e.g. /path/to/file.jpg)',
		displayOptions: { show: showOnlyForFileRename },
	},
	{
		displayName: 'New File Name',
		name: 'newFileName',
		type: 'string',
		required: true,
		default: '',
		description: 'The new name for the file',
		displayOptions: { show: showOnlyForFileRename },
	},
	{
		displayName: 'Purge Cache',
		name: 'purgeCache',
		type: 'boolean',
		default: true,
		description: 'Whether to purge CDN cache for the old file URL',
		displayOptions: { show: showOnlyForFileRename },
	},
	// Bulk Delete
	{
		displayName: 'File IDs',
		name: 'fileIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of file IDs to delete',
		displayOptions: { show: showOnlyForFileBulkDelete },
	},
	// Bulk Add Tags
	{
		displayName: 'File IDs',
		name: 'fileIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of file IDs to add tags to',
		displayOptions: { show: showOnlyForFileBulkAddTags },
	},
	{
		displayName: 'Tags',
		name: 'tags',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of tags to add',
		displayOptions: { show: showOnlyForFileBulkAddTags },
	},
	// Bulk Remove Tags
	{
		displayName: 'File IDs',
		name: 'fileIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of file IDs to remove tags from',
		displayOptions: { show: showOnlyForFileBulkRemoveTags },
	},
	{
		displayName: 'Tags',
		name: 'tags',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of tags to remove',
		displayOptions: { show: showOnlyForFileBulkRemoveTags },
	},
	// Bulk Remove AI Tags
	{
		displayName: 'File IDs',
		name: 'fileIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of file IDs to remove AI tags from',
		displayOptions: { show: showOnlyForFileBulkRemoveAITags },
	},
	{
		displayName: 'AI Tags',
		name: 'tags',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of AI tags to remove',
		displayOptions: { show: showOnlyForFileBulkRemoveAITags },
	},
];

export async function executeFile(
	this: IExecuteFunctions,
	i: number,
): Promise<INodeExecutionData[]> {
	const operation = this.getNodeParameter('operation', i) as string;

	let options: IHttpRequestOptions;

	switch (operation) {
		case 'get': {
			const fileId = this.getNodeParameter('fileId', i) as string;
			options = {
				method: 'GET',
				baseURL: 'https://api.imagekit.io',
				url: `/v1/files/${fileId}/details`,
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			if (Array.isArray(responseData)) {
				return this.helpers.returnJsonArray(responseData as IDataObject[]);
			}
			return [{ json: responseData as IDataObject }];
		}
		case 'delete': {
			const fileId = this.getNodeParameter('fileId', i) as string;
			options = {
				method: 'DELETE',
				baseURL: 'https://api.imagekit.io',
				url: `/v1/files/${fileId}`,
			};
			await this.helpers.httpRequestWithAuthentication.call(this, 'imagekitApi', options);
			return [{ json: { success: true, fileId } as IDataObject }];
		}
		case 'copy': {
			const sourceFilePath = this.getNodeParameter('sourceFilePath', i) as string;
			const destinationPath = this.getNodeParameter('destinationPath', i) as string;
			const includeFileVersions = this.getNodeParameter('includeFileVersions', i) as boolean;
			options = {
				method: 'POST',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/copy',
				body: { sourceFilePath, destinationPath, includeFileVersions },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		case 'move': {
			const sourceFilePath = this.getNodeParameter('sourceFilePath', i) as string;
			const destinationPath = this.getNodeParameter('destinationPath', i) as string;
			options = {
				method: 'POST',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/move',
				body: { sourceFilePath, destinationPath },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		case 'rename': {
			const filePath = this.getNodeParameter('filePath', i) as string;
			const newFileName = this.getNodeParameter('newFileName', i) as string;
			const purgeCache = this.getNodeParameter('purgeCache', i) as boolean;
			options = {
				method: 'PUT',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/rename',
				body: { filePath, newFileName, purgeCache },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		case 'bulkDelete': {
			const fileIds = (this.getNodeParameter('fileIds', i) as string)
				.split(',')
				.map((s) => s.trim());
			options = {
				method: 'POST',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/batch/deleteByFileIds',
				body: { fileIds },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		case 'bulkAddTags': {
			const fileIds = (this.getNodeParameter('fileIds', i) as string)
				.split(',')
				.map((s) => s.trim());
			const tags = (this.getNodeParameter('tags', i) as string).split(',').map((s) => s.trim());
			options = {
				method: 'POST',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/addTags',
				body: { fileIds, tags },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		case 'bulkRemoveTags': {
			const fileIds = (this.getNodeParameter('fileIds', i) as string)
				.split(',')
				.map((s) => s.trim());
			const tags = (this.getNodeParameter('tags', i) as string).split(',').map((s) => s.trim());
			options = {
				method: 'POST',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/removeTags',
				body: { fileIds, tags },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		case 'bulkRemoveAITags': {
			const fileIds = (this.getNodeParameter('fileIds', i) as string)
				.split(',')
				.map((s) => s.trim());
			const tags = (this.getNodeParameter('tags', i) as string).split(',').map((s) => s.trim());
			options = {
				method: 'POST',
				baseURL: 'https://api.imagekit.io',
				url: '/v1/files/removeAITags',
				body: { fileIds, tags },
			};
			const responseData = await this.helpers.httpRequestWithAuthentication.call(
				this,
				'imagekitApi',
				options,
			);
			return [{ json: responseData as IDataObject }];
		}
		default:
			throw new Error(`Unsupported file operation: ${operation}`);
	}
}
